include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - integration_test/**
    - test_backup/**
    - lib/*_backup.dart
    - lib/**/*_backup.dart
    - lib/main_backup.dart
    - lib/**/main_backup.dart
    - lib/firebase_options.dart
    - lib/configs/**
    - lib/core/**
    - lib/data/**
    - lib/domain/**
    - lib/features/**
    - lib/game/**
    - lib/l10n/**
    - lib/logic/**
    - lib/models/**
    - lib/providers/**
    - lib/screens/**
    - lib/state/**
    - lib/systems/**
    - lib/theme/**
    - lib/ui/**
    - lib/utils/**
  errors:
    avoid_print: ignore
    dangling_library_doc_comments: ignore
    dead_code: ignore
    dead_null_aware_expression: ignore
    depend_on_referenced_packages: ignore
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore
    empty_catches: ignore
    invalid_null_aware_operator: ignore
    non_constant_identifier_names: ignore
    prefer_const_constructors: ignore
    unnecessary_dev_dependency: ignore
    unnecessary_import: ignore
    unreachable_switch_case: ignore
    unused_element: ignore
    unused_import: ignore
    unused_local_variable: ignore

linter:
  rules:
    avoid_print: false
    empty_catches: false
    prefer_const_constructors: false
