// File generated by MG-CLI Firebase Setup
// Game ID: 0024
// Project: mg-games-dev
// Auto-generated - Do not edit manually

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError('macOS is not supported');
      case TargetPlatform.windows:
        throw UnsupportedError('Windows is not supported');
      case TargetPlatform.linux:
        throw UnsupportedError('Linux is not supported');
      default:
        throw UnsupportedError('Unknown platform');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCGcPrsolaAKddtr5dzAugwZrSvSXz7wE',  // Shared API key
    appId: '1:701294998464:android:0000000000000018',
    messagingSenderId: '701294998464',
    projectId: 'mg-games-dev',
    storageBucket: 'mg-games-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGZ_0nsZeP8z_hN90984lOLpBUSVgNczU',  // Shared API key
    appId: '1:701294998464:ios:0000000000000018',
    messagingSenderId: '701294998464',
    projectId: 'mg-games-dev',
    storageBucket: 'mg-games-dev.firebasestorage.app',
    iosBundleId: 'com.monthlygames.game0024',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: '1:000000000000:web:0024',
    messagingSenderId: '701294998464',
    projectId: 'mg-games-dev',
    storageBucket: 'mg-games-dev.appspot.com',
    authDomain: 'mg-games-dev.firebaseapp.com',
  );
}
