// File generated by MG-CLI
// Do not edit manually

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError('macOS is not supported');
      case TargetPlatform.windows:
        throw UnsupportedError('Windows is not supported');
      case TargetPlatform.linux:
        throw UnsupportedError('Linux is not supported');
      default:
        throw UnsupportedError('Unknown platform');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: '1:000000000000:android:0024',
    messagingSenderId: '000000000000',
    projectId: 'mg-games-dev',
    storageBucket: 'mg-games-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: '1:000000000000:ios:0024',
    messagingSenderId: '000000000000',
    projectId: 'mg-games-dev',
    storageBucket: 'mg-games-dev.appspot.com',
    iosBundleId: 'com.monthlygames.game0024',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: '1:000000000000:web:0024',
    messagingSenderId: '000000000000',
    projectId: 'mg-games-dev',
    storageBucket: 'mg-games-dev.appspot.com',
    authDomain: 'mg-games-dev.firebaseapp.com',
  );
}
