/// Battle Pass Season 2: Spring Festival Configuration
///
/// Auto-generated by Season 2 deployment script
/// Generated: 2026-04-04T09:30:21.973554
library;

import 'package:mg_common_game/systems/battlepass/battlepass_config.dart';

/// Season 2: Spring Festival Configuration
class Season2Config {
  /// Season ID
  static const String seasonId = 'season_2_spring_festival';

  /// Season Names
  static const String seasonNameKr = '봄 축제 시즌 2';
  static const String seasonNameEn = 'Spring Festival Season 2';

  /// Season Dates
  static const DateTime startDate = DateTime(2026, 4, 1);
  static const DateTime endDate = DateTime(2026, 6, 30);

  /// Season Duration
  static const int seasonDurationDays = 90;

  /// Max Level
  static const int maxLevel = 100;

  /// Premium Price (USD)
  static const double premiumPrice = 9.99;

  /// Spring Festival Theme
  static const BPSeasonTheme springTheme = BPSeasonTheme(
    id: 'spring_festival',
    nameKr: '봄 축제',
    nameEn: 'Spring Festival',
    primaryColor: Color(0xFFFF69B4),
    secondaryColor: Color(0xFFFFB7C5),
    accentColor: Color(0xFFFFD700),
  );

  /// Create Season 2 configuration
  static BPSeasonConfig create() {
    return BPSeasonBuilder.create90DaySeason(
      id: seasonId,
      nameKr: seasonNameKr,
      nameEn: seasonNameEn,
      startDate: startDate,
      maxLevel: maxLevel,
      premiumPrice: premiumPrice,
      theme: springTheme,
    );
  }

  /// Get daily missions for Season 2
  static List<BPMission> getDailyMissions() {
    return BPSeasonBuilder.createSeason2DailyMissions();
  }

  /// Get weekly missions for Season 2
  static List<BPMission> getWeeklyMissions() {
    return BPSeasonBuilder.createSeason2WeeklyMissions();
  }

  /// Get seasonal challenges for Season 2
  static List<BPMission> getSeasonalChallenges() {
    return BPSeasonBuilder.createSeason2SeasonalChallenges();
  }
}
